require:
  - rubocop-performance

Layout/LineLength:
  Max: 120
Naming/AccessorMethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Exclude:
    - 'bin/*'

Lint/MissingSuper:
  Exclude:
    - 'lib/lalamove/services/**/*'
    - 'lib/lalamove/resources/**/*'

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RaiseArgs:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
Style/FrozenStringLiteralComment:
  Enabled: false
  Exclude:
    - 'bin/*'
    - 'spec/*'

